### ISSUE TITLE
Token length exceeds during running simulation

### ISSUE THREAD

**Issue by miracelplus** [PJLab-ADG/DriveLikeAHuman#1]
Hi,

This is Haowei and thanks for the open source code. When I am trying to run the repo, I encountered the following errors:
```
Exception has occurred: InvalidRequestError
This model's maximum context length is 4097 tokens. However, you requested 4270 tokens (3246 in the messages, 1024 in the completion). Please reduce the length of the messages or completion.
```

I am currently using OS Windows 11, Python 3.9.13 Anaconda, and Openai API (rather than the Azure API). I was wondering if you could help solve this issue. Please let me know if other information is required.

Thanks.

**Comment by zijinoier** [comment]
Hi Haowei:
Thanks for your interest of our project! 

It appears that the issue you are facing is due to the high number of tools and ideas that need to be invoked in the decision-making process, causing the token limit of the OpenAI model to be exceeded before a decision can be made. Based on your error message, we guess you're using a `gpt-3.5-turbo` model with only 4k token contexts. However, we recommend using GPT models with at least 8k contexts.

For the OpenAI API, we suggest using either the `gpt-3.5-turbo-16k-0613` or `gpt-3.5-turbo-16k` model, or any `GPT4` model. You can refer to the following link for more details: https://platform.openai.com/docs/models/overview

Specifically, you can modify line 36 on `HELLM.py` with the following code:
```
llm = ChatOpenAI(
    temperature=0.,
    model_name='gpt-3.5-turbo-16k-0613', # or any other model with 8k+ context
    max_tokens=1024
)
```

**Comment by miracelplus** [comment]
Thanks a lot! That solves my question.
