### ISSUE TITLE
Reasoning ability with common sense?

### ISSUE THREAD

**Issue by Dingrui-Wang** [PJLab-ADG/DriveLikeAHuman#2]
I was trying to reproduce the example regarding "Reasoning ability with common sense" with pic below:
![cones_on_truck_1](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/133076790/1c62cacb-f98f-4c2f-a87f-3a20c804738c)

But the result is not expected according to the paper:
![Screenshot from 2023-07-10 22-07-38](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/133076790/24bc8a71-aa72-4e8b-b829-70e45641d8d8)

I am wondering is there anyway we can fix this? Or the result is just not reproducible.
Cheers.

**Comment by zijinoier** [comment]
Hello Dingrui,

Thank you for your valuable feedback. We have also encountered the issue you mentioned during our development process. This is mainly due to the fact that LLMs can still produce unstable and hallucinatory outputs, despite setting the temperature variable to a very low value. Additionally, the final answers can be influenced by the output of the image understanding model.

We would like to offer you some advice to improve the quality of the results:
1. To ensure that the LLM understands your question well, we recommend that you make your question more precise and specific. For instance, in your case, you could try using the question "Should the driver of the 'ego' car decelerate due to the cones on the truck?" instead of referring to "the current situation".
2. Just try again and the answer will be different.:smile:
