### ISSUE TITLE
Could we use GPT-4 model in this scope? 

### ISSUE THREAD

**Issue by Dingrui-Wang** [PJLab-ADG/DriveLikeAHuman#3]
Is it possible for us to use GPT-4 model (with GPT-4 API key in config file) in this project? 
I have tried to replace the API key with a GPT-4 one in `config.yaml` and set the `model_name` of the `llm` in `HELLM.py` as below:
`os.environ["OPENAI_API_KEY"] = OPENAI_CONFIG['OPENAI_KEY']
    llm = ChatOpenAI(
        temperature=0,
        model_name='gpt-4-0613', 
        max_tokens=1024,
        request_timeout=60
    )`
   But we got error: 
   `openai.error.InvalidRequestError: The model: `gpt-4-0613` does not exist`
   
  Thank you in advance for any helpful insight!

**Comment by zijinoier** [comment]
The project supports the GPT-4 model.
From the link https://platform.openai.com/docs/models/overview the model `gpt-4-0613`  do exist, so did you change the value of `OPENAI_API_TYPE` in `config.yaml` to `openai` instead of `azure`?
Also, make sure you did get the api access of GPT4, which you should see `gpt-4-0613` in the list of your account rate-limits https://platform.openai.com/account/rate-limits 

Please let me know if you have solved the problem.

**Comment by Dingrui-Wang** [comment]
> The project supports the GPT-4 model. From the link https://platform.openai.com/docs/models/overview the model `gpt-4-0613` do exist, so did you change the value of `OPENAI_API_TYPE` in `config.yaml` to `openai` instead of `azure`? Also, make sure you did get the api access of GPT4, which you should see `gpt-4-0613` in the list of your account rate-limits https://platform.openai.com/account/rate-limits
> 
> Please let me know if you have solved the problem.

Thx, problem is well solved!
